#!/usr/bin/env perl
use utf8;
use Mojolicious::Lite;
use DateTime;

use Chatbot::Eliza

# Seed the random number generator.
srand( time ^ ($$ + ($$ << 15)) );      

get '/' => 'index';

my $clients = {};

websocket '/echo' => sub {
    my $self = shift;

    app->log->debug(sprintf 'Client connected: %s', $self->tx);
    my $id = sprintf "%s", $self->tx;
    $clients->{$id} = $self->tx;

    $self->on(message => sub {
        my ($self, $msg) = @_;

        my $dt   = DateTime->now( time_zone => 'America/Chicago');

        for (keys %$clients) {
            $clients->{$_}->send({json => {
                hms  => $dt->hms,
                text => $msg,
            }});
        }
    });

    $self->on(finish => sub {
        app->log->debug('Client disconnected');
        delete $clients->{$id};
    });
};

my ($harry, $sally, $he_says, $she_says);
$sally = new Chatbot::Eliza "Sally";
$harry = new Chatbot::Eliza "Harry";
$he_says  = "I am sad.";

my $id = Mojo::IOLoop->recurring(3 => sub {
  my $self = shift;
  $she_says = $sally->transform($he_says);
  chat($sally->name.": $she_says");
  my $id = Mojo::IOLoop->timer(1 => sub {
    $he_says = $harry->transform($she_says);
    chat($harry->name.": $he_says");
  });
});

app->start;

sub chat {
  my $msg = shift;
  my $dt = DateTime->now( time_zone => 'America/Chicago');
  for (keys %$clients) {
    $clients->{$_}->send({json => {
      hms  => $dt->hms,
      text => $msg,
    }});
  }
}

__DATA__
@@ index.html.ep
<html>
  <head>
    <title>WebSocket Client</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="/js/ws.js"></script>
    <style type="text/css">
      textarea {
          width: 40em;
          height:10em;
      }
    </style>
    <script>
      $('textarea').on('change',function(){
      });
    </script>
  </head>
<body>

<textarea id="log" readonly></textarea>
<p><input type="text" id="msg" /></p>

</body>
</html>

@@ js/ws.js
$(function () {
  $('#msg').focus();

  var log = function (text) {
    $('#log').val( $('#log').val() + text + "\n");
    $('#log').scrollTop($('#log').height());
  };

  var ws = new WebSocket('ws://chat.dev.kit.cm/echo');
  ws.onopen = function () {
    log('Connection opened');
  };

  ws.onmessage = function (msg) {
    var res = JSON.parse(msg.data);
    log('[' + res.hms + '] ' + res.text); 
  };

  $('#msg').keydown(function (e) {
    if ( e.keyCode == 13 && $('#msg').val() ) {
      ws.send($('#msg').val());
      $('#msg').val('');
    }
  });
});
