#!/usr/bin/env perl
use utf8;
use Mojolicious::Lite;
use DateTime;

use Digest::MD5 'md5_hex';
use Chatbot::Eliza

# Seed the random number generator.
srand( time ^ ($$ + ($$ << 15)) );      

get '/' => sub {
  my $c = shift;
  $c->session->{user} = $c->param('user');
} => 'index';
get '/js/ws' => 'ws';
get '/css/chat' => 'chat';

my $clients = {};

my ($harry, $sally, $user, $he_says, $she_says, $user_says);

websocket '/echo' => sub {
  my $self = shift;

  app->log->debug(sprintf 'Client connected: %s', $self->tx);
  my $id = sprintf "%s", $self->tx;
  $clients->{$id} = $self->tx;

  $self->on(message => sub {
    my ($self, $msg) = @_;

    my $user = $self->session->{user} || 'John Doe';

    $user_says = $msg;

    my $dt   = DateTime->now( time_zone => 'America/Chicago');

    for (keys %$clients) {
      $clients->{$_}->send($msg);
    }
  });

  $self->on(finish => sub {
    app->log->debug('Client disconnected');
    delete $clients->{$id};
  });
};

$sally = new Chatbot::Eliza "Sally";
$harry = new Chatbot::Eliza "Harry";
$he_says  = "I am sad.";

my $id = Mojo::IOLoop->recurring(3 => sub {
  my $self = shift;
  $she_says = $sally->transform($user_says || $he_says);
  $user_says = undef;
  chat($sally->name, $she_says);
  my $id = Mojo::IOLoop->timer(1 => sub {
    $he_says = $harry->transform($user_says || $she_says);
    $user_says = undef;
    chat($harry->name, $he_says);
  });
});

app->start;

sub chat {
  my ($user, $msg) = @_;
  my $dt = DateTime->now( time_zone => 'America/Chicago');
  my $hms = $dt->hms;
  my $md5 = md5_hex($user);
  for (keys %$clients) {
    $clients->{$_}->send(<<EOF);
<div class="chat-message clearfix">
    <img src="http://gravatar.com/avatar/$md5?d=wavatar&s=32" alt="" width="32" height="32">
    <div class="chat-message-content clearfix">
        <span class="chat-time">$hms</span>
        <h5>$user</h5>
        <p>$msg</p>
    </div>
</div>
<hr>
EOF
  }
}

__DATA__
@@ index.html.ep
<html>
  <head>
    <title>WebSocket Client</title>
    <link href="/css/chat.css" rel="stylesheet">
    <link href="http://localhost:3000/tenant/css" rel="stylesheet">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <script type="text/javascript" src="/js/ws.js"></script>
    <style type="text/css">
      textarea {
          width: 100%;
          height: 90%;
          border-bottom: solid 2px #000;
          margin: 0px;
      }
      input {
        width: 100%;
        height: 10%;
        margin: 0px;
      }
      p {
        margin: 0px;
      }
    </style>
  </head>
<body>

<div id="live-chat">
    <header class="clearfix">
        <h4>Community Chat</h4>
    </header>
    <div class="chat">
        <div id="log" class="chat-history">
        </div>
        <div class="chat-input">
            <p class="chat-feedback">Your partner is typing…</p>
            <form action="#" method="post">
                <fieldset>
                    <input type="text" id="msg" placeholder="Type your message…" autofocus>
                    <input type="hidden">
                </fieldset>
            </form>
        </div>
    </div>
</div>

</body>
</html>

@@ ws.js.ep
$(function () {
  $('#msg').focus();

  var log = function (html) {
    //$('#log').val( $('#log').val() + text + "\n");
    $('#log').append(html);
    //$('#log').scrollTop($('#log')[0].scrollHeight);
  };

  var ws = new WebSocket('<%= url_for('echo')->to_abs %>');
  ws.onopen = function () {
    log('Connection opened');
  };

  ws.onmessage = function (msg) {
    //var res = JSON.parse(msg.data);
console.log(msg.data);
    log(msg.data);
  };

  $('#msg').keydown(function (e) {
    if ( e.keyCode == 13 && $('#msg').val() ) {
      ws.send($('#msg').val());
      $('#msg').val('');
    }
  });

/*
  $('#live-chat header').on('click', function() {
      $('.chat').slideToggle(300, 'swing');
      $('.chat-message-counter').fadeToggle(300, 'swing');
  });

  $('.chat-close').on('click', function(e) {
      e.preventDefault();
      $('#live-chat').fadeOut(300);
  });
*/
});

@@ chat.css.ep
@charset "utf-8";
/* CSS Document */

/* ---------- GENERAL ---------- */

body {
//    background: #e9e9e9;
//    color: #9a9a9a;
    font: 100%/1.5em "Droid Sans", sans-serif;
    margin: 0;
}

a { text-decoration: none; }

fieldset {
    border: 0;
    margin: 0;
    padding: 0;
}

h4, h5 {
    line-height: 1.5em;
    margin: 0;
}

hr {
    background: #e9e9e9;
    border: 0;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
    height: 1px;
    margin: 0;
    min-height: 1px;
}

img {
    border: 0;
    display: block;
    height: auto;
    max-width: 100%;
}

input {
    border: 0;
    color: inherit;
    font-family: inherit;
    font-size: 100%;
    line-height: normal;
    margin: 0;
}

p { margin: 0; font-size: 12px; }

.clearfix { *zoom: 1; } /* For IE 6/7 */
.clearfix:before, .clearfix:after {
    content: "";
    display: table;
}
.clearfix:after { clear: both; }

/* ---------- LIVE-CHAT ---------- */

#l	ive-chat {
    bottom: 0;
    font-size: 12px;
    //right: 24px;
    //position: fixed;
    width: 100%;
}

#live-chat header {
    background: #293239;
    border-radius: 5px 5px 0 0;
    color: #fff;
    cursor: pointer;
    //padding: 16px 24px;
}

#live-chat h4:before {
    background: #1a8a34;
    border-radius: 50%;
    content: "";
    display: inline-block;
    height: 8px;
    margin: 0 8px 0 0;
    width: 8px;
}

#live-chat h4 {
    font-size: 12px;
}

#live-chat h5 {
    font-size: 10px;
}

#live-chat form {
    //padding: 24px;
}

#live-chat input[type="text"] {
    border: 1px solid #ccc;
    border-radius: 3px;
    padding: 8px;
    outline: none;
    width: 90%;
}

.chat-message-counter {
    background: #e62727;
    border: 1px solid #fff;
    border-radius: 50%;
    display: none;
    font-size: 12px;
    font-weight: bold;
    height: 28px;
    left: 0;
    line-height: 28px;
    //margin: -15px 0 0 -15px;
    position: absolute;
    text-align: center;
    top: 0;
    width: 28px;
}

.chat-close {
    background: #1b2126;
    border-radius: 50%;
    color: #fff;
    display: block;
    float: right;
    font-size: 10px;
    height: 16px;
    line-height: 16px;
    margin: 2px 0 0 0;
    text-align: center;
    width: 16px;
}

.chat {
    background: #fff;
}

.chat-history {
    height: 100;
    //padding: 8px 24px;
    overflow-y: scroll;
}

.chat-message {
    //margin: 16px 0;
}

.chat-message img {
    border-radius: 50%;
    float: left;
}

.chat-message-content {
    margin-left: 56px;
}

.chat-time {
    float: right;
    font-size: 10px;
}

.chat-feedback {
    font-style: italic; 
    margin: 0 0 0 80px;
}

.chat-input {
  background: #fff;
  width: 100%;
  position: fixed;
  height: 50px;
  bottom: 0px;
}
